#!/bin/bash

# sends http request to get images from flickr using argument 

wget -O parseThis https://www.flickr.com/search/?text=$1 -q


# parses information put into specified file to only include URLs
input="./parseThis"
while IFS= read -r var
do
	if [[ $var == *"img.src"* ]]; then
		echo "$var" >> imgSrc
	fi
	
done <"$input"

# trims the fat
cat imgSrc | cut -c 18- > tmp
sed 's/..$//' tmp > imageURL

# takes random image from flickr returned results, downloads
#rand=$((($RANDOM % 10) + 1))
line=$(head -n 1 imageURL)
wget -O flag.png $line -q

# cleans up temp files
rm imgSrc
rm tmp
rm parseThis
rm imageURL
